#!/usr/bin/env node
/**
 * Scaffolds a starter YAML for a new exam.
 *
 *   node scripts/init-exam.js
 *   node scripts/init-exam.js --out my-exam.yaml
 *
 * Deliberately small. It asks the few questions whose answers change the
 * structure of the document, picks the archetype column set, and writes a file
 * with one worked skeleton topic and commentary. Everything else is the
 * learner's job — a pre-filled matrix is exactly what the source method says
 * does not work.
 */

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { ARCHETYPES, ARCHETYPE_KEYS } from '../src/lib/archetypes.js';

const argv = process.argv.slice(2);
const outFlag = argv.indexOf('--out');

// Interactive when attached to a terminal; otherwise answers are read from
// piped stdin, one per line, so the scaffolder can be scripted and tested.
const interactive = input.isTTY;
const rl = interactive ? readline.createInterface({ input, output }) : null;
let queued = [];
if (!interactive) {
  const chunks = [];
  for await (const c of input) chunks.push(c);
  queued = Buffer.concat(chunks).toString('utf8').split('\n');
}
const prompt = async (text) => {
  if (interactive) return rl.question(text);
  const a = queued.length ? queued.shift() : '';
  output.write(text + a + '\n');
  return a;
};

const ask = async (q, dflt = '') => {
  const a = (await prompt(dflt ? `${q} [${dflt}]: ` : `${q}: `)).trim();
  return a || dflt;
};
const askOne = async (q, options, dflt) => {
  console.log(`\n${q}`);
  options.forEach((o, i) => console.log(`  ${i + 1}) ${o.label}${o.hint ? ` — ${o.hint}` : ''}`));
  const a = (await prompt(`  choose 1-${options.length} [${dflt}]: `)).trim();
  const i = Number(a) - 1;
  return (i >= 0 && i < options.length) ? options[i].value : options[Number(dflt) - 1].value;
};
const askYN = async (q, dflt = 'n') => {
  const a = (await prompt(`${q} (y/n) [${dflt}]: `)).trim().toLowerCase();
  return (a || dflt).startsWith('y');
};

console.log('\n  Exam Matrix — new exam setup');
console.log('  ────────────────────────────\n');

const name = await ask('Exam name');
if (!name) { console.log('An exam name is required.'); if (rl) rl.close(); process.exit(1); }

const lang = await askOne('Document language', [
  { value: 'en', label: 'English' },
  { value: 'ko', label: '한국어' },
], '1');

const authority = await ask('Awarding body', '');
const date = await ask('Exam date (YYYY-MM-DD)', '');
const passing = await ask('Passing criterion', '');
const version = await ask('Syllabus / version you are studying', '');
const subjects = (await ask('Subjects, comma separated', '')).split(',').map((s) => s.trim()).filter(Boolean);

const archetype = await askOne('Mainly which kind of material?', [
  ...ARCHETYPE_KEYS.map((k) => ({ value: k, label: ARCHETYPES[k].label, hint: ARCHETYPES[k].blurb })),
], '1');

const needsVersioning = await askYN('\nDoes the content change between sittings (law, tax, specs)?',
  archetype === 'law' ? 'y' : 'n');

console.log('');
const arch = ARCHETYPES[archetype];
const cols = arch.columns.filter((c) => c.default);
const extra = arch.columns.filter((c) => !c.default);

const q = (s) => (s === '' ? "''" : (/[:#\-{}[\]&*!|>'"%@`,]/.test(String(s)) ? `'${String(s).replace(/'/g, "''")}'` : s));
const L = (k, v) => `  ${k}: ${q(v)}`;

const yaml = `# ${name}
# Generated by scripts/init-exam.js. Everything below is a starting point.
#
# The one rule that matters: the columns must be the axes THIS exam actually
# discriminates on. The defaults below come from the "${archetype}" archetype;
# replace them as soon as you have seen real questions. Do not keep a column
# just because it was generated.

exam:
${L('name', name)}
${L('lang', lang)}
${authority ? L('authority', authority) + '\n' : ''}${date ? L('date', date) + '\n' : ''}${passing ? L('passing', passing) + '\n' : ''}${version ? L('syllabus_version', version) + '\n' : ''}  target_score:
  confidence: 1
  last_updated: '${new Date().toISOString().slice(0, 10)}'
${subjects.length ? `  subjects:\n${subjects.map((s) => `    - ${q(s)}`).join('\n')}\n` : '  subjects: []\n'}  sources: []

  # What does this exam actually reward, as opposed to what the syllabus lists?
  # Write this after your first past paper, not before.
  what_it_tests:
    -

  blueprint:
    - domain: ${q(subjects[0] ?? (lang === 'ko' ? '첫 번째 영역' : 'First domain'))}
      weight:
      question_type:
      priority: A
      confidence: 1
      last_review:

  high_yield: []
  weak: []
${needsVersioning
  ? '  # Content that changes between sittings. Re-verify every item here before the exam.\n  volatile:\n    -\n'
  : '  volatile: []\n'}
topics:
  - id: first-topic
    title: ${q(lang === 'ko' ? '첫 번째 주제 — 제목을 바꾸세요' : 'First topic — rename me')}
    archetype: ${archetype}
    importance: A
    frequency:
    why:
    core_question:
    key_axis:
    prerequisites: []
    sources: []
    updated: '${new Date().toISOString().slice(0, 10)}'

    # Leave blank and write it by hand, or fill it in and let the Recall
    # Edition blank it for you.
    one_sentence:

    # Five maximum. The cap is the point.
    essentials:
      -

    matrix:
      row_label: ${q(lang === 'ko' ? arch.row_label_ko : arch.row_label)}
      # layout: auto | portrait | landscape
      columns:
${cols.map((c) => `        - { key: ${c.key}, label: ${q(c.label)}, label_ko: ${q(c.label_ko)}, mark: ${c.mark} }`).join('\n')}
      # Other columns this archetype offers — uncomment what the exam tests:
${extra.map((c) => `      # - { key: ${c.key}, label: ${q(c.label)}, label_ko: ${q(c.label_ko)}, mark: ${c.mark} }`).join('\n')}
      rows:
        - label: ${q(lang === 'ko' ? '항목 A' : 'Item A')}
          cells:
${cols.map((c) => `            ${c.key}:`).join('\n')}
        - label: ${q(lang === 'ko' ? '항목 B' : 'Item B')}
          cells:
${cols.map((c) => `            ${c.key}:`).join('\n')}

    decisive:
      # If an examiner forced you to separate these rows using ONE criterion,
      # what would it be?
      answer:
      pairs:
        - a: ${q(lang === 'ko' ? '항목 A' : 'Item A')}
          b: ${q(lang === 'ko' ? '항목 B' : 'Item B')}
          why:
          clue:

    traps:
      - cue: ${q(lang === 'ko' ? '시험에 나오는 진술을 그대로 옮겨 적으세요' : 'Paste the statement in the wording the exam uses')}
        usually:
        exception:
        why:
        source:

    evidence:
      - cell: { row: ${q(lang === 'ko' ? '항목 A' : 'Item A')}, column: ${cols[0].key} }
        source:
        exam:
        question:
        tested_as:
        risk: high

# Each entry must name the matrix cell it invalidates. That link is the whole
# system: a mistake is not logged, it is routed.
error_log:
  - date:
    question:
    topic:
    mine:
    correct:
    error_type: knowledge-gap
    missing_distinction:
    matrix_update: { topic: first-topic, row: ${q(lang === 'ko' ? '항목 A' : 'Item A')}, column: ${cols[0].key} }
    retest:

compression:
  l2: []
  l3: []

blank_rows:
  error_log: 9
`;

const dest = outFlag >= 0
  ? argv[outFlag + 1]
  : path.join('examples', `${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'new-exam'}.yaml`);

fs.mkdirSync(path.dirname(dest), { recursive: true });
if (fs.existsSync(dest)) {
  const ok = await askYN(`\n${dest} exists. Overwrite?`, 'n');
  if (!ok) { console.log('Aborted.'); if (rl) rl.close(); process.exit(0); }
}
fs.writeFileSync(dest, yaml);
if (rl) rl.close();

console.log(`\n  Wrote ${dest}`);
console.log(`  Next:  node scripts/build.js ${dest}`);
console.log('         then open output/examples/ — or pass --primary to claim the top-level filenames.\n');
